name: senior_fitness_app
description: App de ejercicios para adultos mayores guiada por Sofi, la entrenadora virtual
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  Firebase (versiones estables y compatibles entre sí)
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4
  firebase_analytics: ^10.10.7   # compatible con firebase_core 2.x
  image_picker: ^1.1.1

  #  HTTP y APIs externas
  http: ^1.1.0
  googleapis: ^15.0.0

  #  Almacenamiento local
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0

  #  Utilidades
  intl: ^0.19.0
  equatable: ^2.0.5

  #  UI y diseño
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.1
  lottie: ^3.3.2
  google_fonts: ^6.2.0
  animations: ^2.0.10
  confetti: ^0.7.0

  #  Notificaciones locales + zonas horarias
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.1

  #  IA (Gemini)
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animations/sofi_wave.json
    - assets/animations/sofi_thinking.json
    - assets/animations/sofi_waving.json
    - assets/animations/Trophy.json
    - assets/animations/xp_star.json
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
